### ISSUE TITLE
The font in usual emails from redmine became lower after installing Reminder

### ISSUE THREAD

**Issue by ppoektos** [Hopebaytech/redmine_issue_reminder#18]

**Comment by ppoektos** [comment]
http://i.piccy.info/i9/9aa197b1aa3fc8d48efa51c810390255/1426857240/44625/886060/reminder_font.png

**Comment by Androc** [comment]
Hello.

Maybe you updated a gem while installing the plugin?

**Comment by ppoektos** [comment]
No.
After removing prototype-rails gem font in emails from redmine returned.
But now emails from Reminder looks without style.

**Comment by jcppkkk** [comment]
Nailed it. :sunglasses: 
reminder uses premailer-rails to render CSS style: https://github.com/fphilipe/premailer-rails
> premailer-rails processes all outgoing emails by default. If you wish to skip premailer for a certain email, simply set the :skip_premailer header


So i setting ```ActionMailer::Base.default :skip_premailer => true``` in ```init.rb``` to suppress premailer-rails. (However it will also stops all other mails's CSS style if other plugin happens to use premailer-rails, too.)

Then use ```headers[:skip_premailer] = nil``` remove the flag in view. but that's because i don't know where to put it. :ghost: There should be a better place to do this.
