### ISSUE TITLE
cron does not send mails / test e mails are sent

### ISSUE THREAD

**Issue by missionmedia** [Hopebaytech/redmine_issue_reminder#3]
Hello Hopebaytech,
thank to fork this plugin. It is exactly what we need.
However, the cron job does not send mails. The test call but sends e-mails. If you have a tip for me, I would be very grateful to them.

King regards
Jürgen

**Comment by Androc** [comment]
I have exactly the same problem you had @OrbHacker except I am unable to solve it because I have "no error" as you had ("/usr/bin/env: ruby_executable_hooks: No such file or directory").
I used several version of rake on my server, with and without option -f, etc.

rake reminder:exec does not send email while rake reminder:exec[test] send email.

I think I have correctly configured the plugin by giving it a request that returns issues, but no mail :(

Environment:
  Redmine version                2.6.1.stable
  Ruby version                   1.9.3-p194 (2012-04-20) [i486-linux]
  Rails version                  3.2.21
  Environment                    production
  Database adapter               Mysql2
SCM:
  Mercurial                      2.2.2
  Git                            1.7.10.4
  Filesystem
Redmine plugins:
  redmine_checklists             3.0.2
  redmine_dashboard              2.5.0
  redmine_issue_reminder         0.0.1
  redmine_lightbox2              0.1.2
  redmine_mentions               0.0.1
  scrum                          0.8.0

**Comment by missionmedia** [comment]
Hey, i have a new error. If we try to run we get the following. 

DEPRECATION WARNING: The InstanceMethods module inside ActiveSupport::Concern will be no longer included automatically. Please def
ine instance methods directly in #<Module:0x000000036dca10> instead. (called from <top (required)> at /var/lib/redmine-2.5.2/plugi
ns/redmine_issue_reminder/app/models/issue_reminder_mailer.rb:1)

I think its a small one. hope you can help. 

Thanks!

**Comment by Androc** [comment]
I found where my problem was.

I was fooled by an other issue I had : #8 

I assumed `rake reminder:exec[test]` only sent "test emails" with no body, just to show that sending emails works.

In fact, `rake reminder:exec[test]` is supposed to have exactly the same behavior as `rake reminder:exec` except two things :
* it does always send emails (no matter when the last execution was)
* it does not update the last execution date

So, the behavior of `rake reminder:exec` is to send email only if it is time to send a new email, regarding the interval parameters and the `rake reminder:exec[test]` is supposed to send email each times it is executed with a non empty body.

I found a fix for the issue #8 and made a pull request.

**Comment by jcppkkk** [comment]
@Androc , the behavior of `rake reminder:exec[test]` you described is exactly what i designed -- to give a quick test without check or modify last execution date. I have update that to README. 
Maybe i will add `rake reminder:exec[reset_scheduler]` someday.

**Comment by Androc** [comment]
@jcppkkk, thank you, I think it is perfectly clear.

PS : If you have time, I think you could update the "migrate" part of the README. `rake db:migrate:plugins` is for Redmine 1.X if I am not wrong.
For Redmine 2.X you are support to use `rake redmine:plugins:migrate`

**Comment by jcppkkk** [comment]
Update README for some detailed information. This issue about cron / test emails should be closed now.
